### ISSUE TITLE
[FR] [6axis_dev] 6 axes broken with certain configs and G-codes. Add Sanity checks!

### ISSUE THREAD

**Issue by DerAndere1** [DerAndere1/Marlin2ForPipetBot#13]
### Description

Marlin support for 6 axes (XYZIJK + E) works only for certain configs and only a subset of G-codes is supported at the moment. I suggest to collect a whitelist of working features 

**Expected behavior:** [What you expect to happen]
add sanity checks against any non-working config settings. 

**Actual behavior:** [What actually happens]
some config combination may not compile with NON_E_AXES > 3, some configs may compile but may not work in practice. 

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by DerAndere1** [comment]
Currently the configs by hobiseven are the only ones that were tested. Below I list Individual features that may work (although not all combinations). All other config settings currently should be treated as not supported yet. 

- *_DRIVER_TYPE A4988
- *_DRIVER_TYPE DRV8825
- *_DRIVER_TYPE TMC5160
- LINEAR_AXES 3
- LINEAR_AXES 4
- LINEAR_AXES 5
- EXTRUDERS 0
- EXTRUDERS 1
- EXTRUDERS 2
- [DEBUG_LEVELING;], [DEBUG_PINS;]
- [dogm display (possibly not all menus work flawlessly with axes I,J,K)]
- One stepper driver per axis

Boards:
- ANET_10 // Melzi_optiboot
- RAMPS_14_EFB
- MKS Rumba32
- ALFAWISE_U20 (?)
- ALFAWISE_U30 (?)
- Teensy 3.6
- MEGATRONICS_3

The following G-codes were tested:

- G1 F500; G1 X10; G1 Y10; G1 Z10; G1 A10; G1 B10; G1 X10 Y10 Z10; 
- G1 X10 Y10 Z10 I10; G1 X10 Y10 Z10 B10; G1 X10 Y10 Z10 A10 B10; G1 A10 B10; 
- M17; M18; M19
- G28; G28 X; G28 Y; G28 Z; G28 A; G28 B; 
- G90; G91
- M43 E1
- M92
- M111
- M114; M114 D (?)
- M119
- M140
- M280
- M400
- M206 (?)
- M500; M501; M502; M503; M504
- T0, T1

**Comment by hobiseven** [comment]
Added to the white list : 
M17 M18 M85
M501
