### ISSUE TITLE
Menu_motion.cpp bug Marlin-bf2_6axis_dev14

### ISSUE THREAD

**Issue by heppstar** [DerAndere1/Marlin2ForPipetBot#18]
Hi,

Found a little BUG:

**menu_motion.cpp Line 102-113**

     case I_AXIS:
            TERN_(MIN_SOFTWARE_ENDSTOP_I, min = soft_endstop.min.i; <----- MISSING **)**
            TERN_(MIN_SOFTWARE_ENDSTOP_I, max = soft_endstop.max.i; <----- MISSING **)**
          #if NON_E_AXES > 4
            break;
            case J_AXIS:
            TERN_(MIN_SOFTWARE_ENDSTOP_J, min = soft_endstop.min.j; <----- MISSING **)**
            TERN_(MIN_SOFTWARE_ENDSTOP_J, max = soft_endstop.max.j; <----- MISSING **)**
            #if NON_E_AXES > 5
              break;
              case K_AXIS:
                TERN_(MIN_SOFTWARE_ENDSTOP_K, min = soft_endstop.min.k; <----- MISSING **)**
                TERN_(MIN_SOFTWARE_ENDSTOP_K, max = soft_endstop.max.k; <----- MISSING **)**
            #endif
          #endif

**Comment by DerAndere1** [comment]
thanks for providing a fix. this will be a short lived issue.
