### ISSUE TITLE
[Bug] [bf2_6axis_dev14] regression: IJK endstop validation during homing kills printer

### ISSUE THREAD

**Issue by DerAndere1** [DerAndere1/Marlin2ForPipetBot#19]
### Description

Regression: axis I moves with G1 but does not move during G28 auto home. Therefore, IJK endstop validation during homing kills the machine.  

### Steps to Reproduce

1. Upload bf2_6axis_dev14
2. send G28

**Expected behavior:** [What you expect to happen]

G28 should sucessfully home axesall axes.

**Actual behavior:** [What actually happens]

After homing of XYZ, axis I it does not move during G28. Because I endstops are not triggered, `endstop_validation()` in motion.cpp results in the kill error message 

#### Additional Information

This bug was not present in bf2_6axis_dev13 or bf2_6axis_dev12

**Comment by heavylight-repo** [comment]
Did you find any solution to this problem?

**Comment by DerAndere1** [comment]
Should be fixed with today's commit. Reopen if you still encounter this bug
