### ISSUE TITLE
IJK axis moves very slow on first move

### ISSUE THREAD

**Issue by heppstar** [DerAndere1/Marlin2ForPipetBot#21]
### Description

IJK axis moves very slow on first move

Hardware: Prototype Robot with SKR PRO v1.1 and six axis (TMC2209)
Marlin Dist: BF2_6axis_dev14 0f8be77

### Steps to Reproduce

1. Send "G1 I100.0 F3000" from Pronterface
2. Send "G1 I200.0 F3000" from Pronterface
3. Send "G1 I300.0 F3000" from Pronterface

**Expected behavior:** [What you expect to happen]

1. "I" moves normal speed to the right
2. "I" moves normal speed to the right
3. "I" moves normal speed to the right

**Actual behavior:** [What actually happens]

1. "I" moves very slow to the right
2. "I" moves normal speed to the right
3. "I" moves normal speed to the right

#### Additional Information

Same behavior on IJK-axis

I would be glad help you test all the new commits that are coming! This is the best project ever on Github! :)

#### My config
[Config_files.zip](https://github.com/DerAndere1/Marlin/files/4859386/Config_files.zip)

**Comment by DerAndere1** [comment]
Thanks for testing and reporting Sorry for the late replies. Is this bug still occuring with the recent commit to the bf2_6axis_dev14 branch?

**Comment by DerAndere1** [comment]
With https://github.com/DerAndere1/Marlin/tree/6axis_dev it should work if you send M502 as the first command after connecting to the printer. I will close this bug report because the underlying issue is likely related to a EEPROM datasize error, issue https://github.com/DerAndere1/Marlin/issues/25 .
