### ISSUE TITLE
Compilation Bug

### ISSUE THREAD

**Issue by heppstar** [DerAndere1/Marlin2ForPipetBot#22]
### Description

Some compilation bugs.

Hardware: Prototype Robot with SKR PRO v1.1 and six axis (TMC2209)
Marlin Dist: BF2_6axis_dev14 0f8be77

#### Configuration_store.cpp Line 3418-3427 gives compile error "can not start with ||"...
      #if AXIS_IS_TMC(X) || AXIS_IS_TMC(Y) || AXIS_IS_TMC(Z) 
        #if NON_E_AXES > 3
          || AXIS_IS_TMC(I)
          #if NON_E_AXES > 4
            || AXIS_IS_TMC(J) 
            #if NON_E_AXES > 5
              || AXIS_IS_TMC(K)
            #endif
          #endif
        #endif

**Expected behavior:** [What you expect to happen]

Compilation

**Actual behavior:** [What actually happens]

No compilation

#### Additional Information

I would be glad help you test all the new commits that are coming! This is the best project ever on Github! :)

#### My config
[Config_files.zip](https://github.com/DerAndere1/Marlin/files/4859386/Config_files.zip)

**Comment by DerAndere1** [comment]
Should be fixed with today's commit. Reopen if you still encounter this bug
