### ISSUE TITLE
Can not compile with MONITOR_DRIVER_STATUS and TMC_DEBUG activated

### ISSUE THREAD

**Issue by heppstar** [DerAndere1/Marlin2ForPipetBot#23]
### Description

Some compilation bugs.

Hardware: Prototype Robot with SKR PRO v1.1 and six axis (TMC2209)
Marlin Dist: BF2_6axis_dev14 0f8be77

### Steps to Reproduce

In "configuration_adv.h"
1. Uncomment #define TMC_DEBUG
2. Uncomment #define MONITOR_DRIVER_STATUS

**Expected behavior:** [What you expect to happen]

Compilation

**Actual behavior:** [What actually happens]

No compilation

#### Additional Information

It works without MONITOR_DRIVER_STATUS and TMC_DEBUG

I would be glad help you test all the new commits that are coming! This is the best project ever on Github! :)

#### My config
[Config_files.zip](https://github.com/DerAndere1/Marlin/files/4859386/Config_files.zip)

**Comment by DerAndere1** [comment]
Should be fixed with today's commit. Reopen if you still encounter this bug
