### ISSUE TITLE
[bug] [Marlin2ForPipetBot] [6axis_dev] EEPROM Error: Field planner_leveling_active mismatch

### ISSUE THREAD

**Issue by DerAndere1** [DerAndere1/Marlin2ForPipetBot#25]
### Description

With branch 6axis_dev as well as Marlin2ForPipetbot, EEPROM cannot be validated. M504 does NOT print "EEPROM OK" to stdout.

### Steps to Reproduce

1. enable (uncomment) option `#define EEPROM_SETTINGS` and `#define EEPROM_CHITCHAT` in configuration.h
2. reflash
3. Open Printrun pronsole and enter
```
connect
M502
M500
M504
```

**Expected behavior:** 
"EEPROM OK" printed to the console of pronsole

**Actual behavior:**
M500 yields "error: EEPROM datasize error"
M504 yields 
```
error: EEPROM datasize error
echo: index: 645 Size 737
```
No "EEPROM OK" is printed to the console of pronsole 

#### Additional Information

None

**Comment by DerAndere1** [comment]
Error: Field planner_leveling_active mismatch

**Comment by DerAndere1** [comment]
I guess we need to add dummy values somewhere between the last passing `_FIELD_TEST` and  `_FIELD_TEST(planner_leveling_active);`. See settings.cpp lines 702 - 755 and lines 1602 - 1651 .

**Comment by bilsef** [comment]
#36 fixes this issue.

**Comment by DerAndere1** [comment]
Thanks, I did not test in hardware but the code changes from PR https://github.com/DerAndere1/Marlin/pull/36 look absolutely fine, so I close this as fixed. Will reopen if this is still an issue. Thanks once again, @bilsef

**Comment by DerAndere1** [comment]
Not fixed for me on a Melzi clone

**Comment by bilsef** [comment]
What output do you get from M500 and M504?  I tried a couple of different boards and all axis settings and it worked.  There are a lot of settings that can change what is stored, and I have not tried them all, so maybe it is some particular combination that is causing the problem

>>> m500
SENDING:M500
echo:Settings Stored (733 bytes; crc 20487)
>>> m504
SENDING:M504
echo:EEPROM OK

**Comment by DerAndere1** [comment]
Hah, it was indeed fixed by your PR. I missed one changed line when backporting it to my testing branch. Sorry for the noise. This is awesome. Closing as fixed again.
