### ISSUE TITLE
SENSORLESS_HOMING with TMC5160

### ISSUE THREAD

**Issue by DigDagGoo** [DerAndere1/Marlin2ForPipetBot#43]
SENSORLESS_HOMING with TMC5160 (Axis I) doesn't work 

### Steps to Reproduce

#define NON_E_AXES 4
#define TMC_USE_SW_SPI 
#define TMC_DEBUG
#define ??_DRIVER_TYPE TMC5160 (for all Stepper)
#define SENSORLESS_HOMING
#define I_STALL_SENSITIVITY  4
#define I_MIN_ENDSTOP_INVERTING true
#define USE_IMIN_PLUG
#define I_HOME_DIR -1
#define I_MIN_PIN       PF12 (BTT GTR and M5 Board)

"SENSORLESS_HOMING" caused a compile error.

I changed the line in TMC_Util.h as follows
   struct sensorless_t {bool LIST_N (NON_E_AXES, x, y, z, i, j, k), x2, y2, z2, z3, z4; }; 

**Expected behavior:** 
The sensorless homing process (eg X28 I) should be work for all non E Axis. The TMC5160 stall detection should set the diag1 pin for a short time to L, which can be evaluated via the switch (I_MIN_PIN).  

**Actual behavior:**
I can see (with my osciloscope) that the register 0x6D (Bit 16-19, sgt0,1,2,3) from the corresponding TMC Chip will be set with the correct value "4" if i send a M914 I4... this looks pretty good. But the Diag1 Pin will not reflect a stall detection.

If i use instead of the diag1 stuff the beta function "SPI_ENDSTOPS",  a stall detection will also never detected...

on X and y Axis (also with dual stepper) everything works fine... only I (in my case) don't.

As a result, no stall detection is available for axis I on the DIAG1 pin which can be evaluated via the switch (I_MIN_PIN).

**Comment by DerAndere1** [comment]
@DiagDagGoo could you briefly explain how you resolved this issue? That would be awesome.
