### ISSUE TITLE
Limit switch problem

### ISSUE THREAD

**Issue by yunxiang521** [DerAndere1/Marlin2ForPipetBot#45]
i. Whether J and K can be set independently and whether limit switches are needed is very inconvenient sometimes if they have to be used

**Comment by DerAndere1** [comment]
Is the process of configuring limit switches for axes I, J and K different from  configuring limit switches for XYZ ?

**Comment by yunxiang521** [comment]
Yes, I, J limited switch function is not required, I and j are used for functions like e-axis.

**Comment by DerAndere1** [comment]
I want I, J, K to behave exactly like X,Y,Z. If this is currently the case, your request won't get adressed. If axes  I,J,K currently behave different from X,Y,Z, please report.
