### ISSUE TITLE
I axis only works in absolute positioning 

### ISSUE THREAD

**Issue by alana12345** [DerAndere1/Marlin2ForPipetBot#54]
Hello,

I am new to Marlin and having an issue with the I axis (4th axis). The stepper motor only runs in absolute coordinates. For example, even if I send a G91 command, the I axis will treat any following commands as absolute coordinates rather than relative. This is not true of the X,Y, and Z axes--they all work perfectly. Any help would be greatly appreciated! Thank you. 

### Steps to Reproduce

1. Send G91 command
2. Send G1 I10 command (or other command)
3. I axis treats command as absolute positioning rather than relative

**Expected behavior:** 
I axis moves in relative when G91 command is given preceding G1 commands 

**Actual behavior:** 
I axis moves in absolute positioning always

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[Marlin-Marlin2ForPipetBot.zip](https://github.com/DerAndere1/Marlin/files/7040660/Marlin-Marlin2ForPipetBot.zip)

**Comment by DerAndere1** [comment]
thanks for reporting. I will check

**Comment by DerAndere1** [comment]
In some days, after the pull request 22599 "Rework G2/G3 arc handling" will be merged into  upstream MarlinFirmware/Marlin, I will release a new version of Marlin2ForPipetBot where relative positioning works

**Comment by alana12345** [comment]
Great! Thank you. Looking forward to the new version.

**Comment by DerAndere1** [comment]
Does this bug also happen if you do not use the display at all but send all commands to the printer via USB using a host software such as printrun or repetier host?

**Comment by alana12345** [comment]
I have only been running the printer with printrun, don't have an LCD screen or anything.

**Comment by DerAndere1** [comment]
I released a new version of Marlin2ForPipetBot: https://github.com/DerAndere1/Marlin/releases/ .
It is up to date with branch https://github.com/DerAndere1/Marlin/tree/Marlin2ForPipetBot as of today and I have no problems with relative/ absolute mode (G90 or G91).

**Comment by alana12345** [comment]
Great, will test it out soon. Thank you!

________________________________

**Comment by DerAndere1** [comment]
Sorry, this isprobably still not fixed for some setups.  See upstream issue https://github.com/MarlinFirmware/Marlin/issues/22681 .

**Comment by DerAndere1** [comment]
This should now be fixed in https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Comment by alana12345** [comment]
That works, thank you so much!

________________________________
