### ISSUE TITLE
problem with I J K sensorless homing

### ISSUE THREAD

**Issue by rds11080** [DerAndere1/Marlin2ForPipetBot#61]
hi, i get the 6 axis working but i try to use the sensorless homing, only X Y Z sensorless homing work, A B C keep moving without stop, and the stallguard threshold is 0, i try google but cant find anything? any ideal how to get A B C sensorless homing to work? thanks

**Comment by DerAndere1** [comment]
closing. This is discussed upstream in https://github.com/MarlinFirmware/Marlin/issues/22649
