### ISSUE TITLE
[FR] replace workaround for wrong internal steps per mm by a proper fix

### ISSUE THREAD

**Issue by DerAndere1** [DerAndere1/Marlin2ForPipetBot#7]
### Description

With the branch https://github.com/DerAndere1/Marlin/tree/6axis_dev and https://github.com/DerAndere1/Marlin/tree/6axis_PR1, axis I moves slower and less far than expected. When the DEFAULT_MAX_FEEDRATE and STEPS_PER_UNIT for the axes IJK in Configuration.h is set to the same value as for the Z axis, IJK move slower and less far than Z.

### Steps to Reproduce

Set DEFAULT_MAX_FEEDRATE and STEPS_PER_UNIT if the I axis to the same value as for the Z axis

**Expected behavior:** Same speed for I and Z

**Actual behavior:** I moves slower than Z

#### Additional Information

Regression (bug is not present in branch https:/github.com/DerAndere1/Marlin/tree/Marlin2ForPipetBot which is based on pre-release Marlin-bugfix2.0.x)

**Comment by hobiseven** [comment]
This is no longer an issue for the Gcodes. 
Still and issue for move menus. See other issue opened.

**Comment by DerAndere1** [comment]
This issue is about the updated branch bf2_6axis_dev as  noted in the description and I think it is still not fixed there.

**Comment by DerAndere1** [comment]
6axis_dev contains a work-around. A proper fix of the underlying issue still should replace the work-around in the future. Pull requests are welcome.

**Comment by DerAndere1** [comment]
Finally fixed thanks to bilsefs PR https://github.com/DerAndere1/Marlin/pull/31
